# Generated by Django 5.0.1 on 2024-02-17 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_video_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
